### ISSUE TITLE
Hash arguments

### ISSUE THREAD

**Issue by erjohnson** [josephyi/taric#5]
Hello! Figured I'd help with documenting more of this lib, came across a lot of instances where a hash is the expected input on a method:

``` ruby
def summoners_by_names(summoner_names:)
  response_for SUMMONERS_BY_NAMES, {summonerNames: summoner_names}
end
```

So you end up writing:

``` ruby
summoners = client.summoners_by_name(summoner_names: 'C9 Sneaky,Maknoon')
```

Perhaps doing something like:

``` ruby
def summoners_by_ids(*summoner_ids)
  response_for SUMMONERS_BY_IDS, { summonerIds: [summoner_ids].join(',') }
end
```

So the input could be:

``` ruby
summoners = client.summoners_by_name('C9 Sneaky', 'Maknoon')
# or
summoners = client.summoners_by_name(['C9 Sneaky', 'Maknoon'])
```

Thoughts?

**Comment by austinrfnd** [comment]
@erjohnson This makes a lot of sense personally assuming we the gem explicitly states in the documentation Ruby >= 2.

**Comment by josephyi** [comment]
Hey, @erjohnson, thanks for helping and the feedback! Those are actually [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments), not options hash arguments. They look similar in practice, but you wouldn't be able to do something like:

``` ruby
hash = {summoner_names: 'lzrface,ipa,dbanksdesign'}
summoners = client.summoners_by_names(hash)
# ArgumentError: missing arg summoner_names or something to that effect
```

Keyword arguments might seem a little painful at first, but they're usefulness outweighs the inconvenience, imho.

As for your suggestions, this was actually one of the philosophical points of contention I faced when designing the method signatures. Since the original goal of this gem was to provide a very close mapping to Riot's API, I ultimately decided against abstracting the input values for the endpoints i.e. for a given param, if Riot's endpoint is expecting a comma delimited string, then Taric too will expect a comma delimited string. Since API wrappers are all inherently leaky abstractions, and Taric was already abstracting a lot of the endpoint url (host, region, api key, and whether the arg is for path or query param), I decided to draw the line here out of principle.

I'll keep the issue open to allow for more discussion (it was 6:00 am in Korea when I got this, so I'm not fully awake). Again, thanks for the feedback. Looking forward to a PR!
